### PR TITLE
[WIP] [JOSS] Implement testing matrix

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR is the first attempt to implement a testing matrix (see [this comment](https://github.com/ni1o1/transbigdata/issues/6#issuecomment-1024923067)) for:
* Ubuntu
* Python 3.{7,8,9}

### CODE REVIEW

**Comment by jGaboardi** [comment]
@ni1o1 I was still working on this, but can continue in another PR.

**Comment by ni1o1** [comment]
Sorry, my mistake

**Comment by jGaboardi** [comment]
No problem at all! For reference, many contributors may add a `[WIP]` tag (work in progress) to the title of a PR until it is ready for review. Others may also simply create a Draft PR.

**Comment by ni1o1** [comment]
OK! Thanks!

**Pull request merged**
